name: vrt-capture

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  capture:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      statuses: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false

      - id: rust-toolchain
        uses: dtolnay/rust-toolchain@stable # zizmor: ignore[unpinned-uses] rust-toolchain channel aliases are intentionally used

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ format('rust-{0}-cargo-{1}', runner.os, hashFiles('Cargo.lock')) }}
          restore-keys: |
            ${{ github.event_name == 'pull_request' && format('rust-{0}-cargo-', runner.os) }}

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: target
          key: ${{ format('rust-{0}-target-vrt-{1}-{2}', runner.os, steps.rust-toolchain.outputs.cachekey, hashFiles('Cargo.lock')) }}
          restore-keys: |
            ${{ github.event_name == 'pull_request' && format('rust-{0}-target-vrt-', runner.os) }}

      - run: cargo fetch --locked

      - run: bash ./.github/scripts/capture_vrt_data.sh

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: vrt-data
          path: data

      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          SUCCESSOR_NAME: ${{ github.event_name == 'pull_request' && 'pr_checks' || 'publish_baseline' }}
        with:
          script: |
            const { owner, repo } = context.repo;
            const sha = context.payload.pull_request?.head?.sha || context.sha;
            
            await github.rest.repos.createCommitStatus({
              owner, repo, sha,
              state: "pending",
              context: `vrt-report / ${process.env.SUCCESSOR_NAME}`,
            });
